### ISSUE TITLE
Feature Request: Combine Multiple PNGs Into a Single ICO

### ISSUE THREAD

**Issue by toddjames** [adv12/IcollatorForever#1]
Hello,

Thanks for this tool! I'm not sure if I just don't understand how to use it or if this feature doesn't exist currently, but I often have a need to upload multiple source PNG files of various sizes (16x16 all the way to 256x256) and combine them into a single ICO file. There used to be another web-based tool that did this, which is now defunct. Would the be possible to implement in IcollatorForever?

Thanks!

**Comment by adv12** [comment]
Hi Todd.  This works if you drag multiple PNGs onto the window or select multiple in the file dialog.  Then you'll get prompted for each PNG what variations to generate from it.  Since you're supplying all the source PNGs yourself, you can just check the one checkbox for the format of the one you're currently being prompted about.

**Comment by adv12** [comment]
This tool was a port of a simpler Windows app mostly for experimenting with Blazor, and the UI really sucks.  Apologies for that.

**Comment by toddjames** [comment]
Ah, I see - that does work. Thank you!

**Comment by janbrasna** [comment]
Nah, it works wonders!! It just isn't obvious when you start with the first asset that you will be given similar page for every other uploaded image too, to mix & match the sizes and encoding as you see fit. I think it's just brilliant! and only needs a little trial and error to get familiar with the workflow, to know what to expect the next time;) Sure, a small copywriting improvements might hint at how to progress through the forms, but it only really takes one or two tries to be certain the next time.

Thanks for it!
